### ISSUE TITLE
Add Skia

### ISSUE THREAD

**Issue by 0joshuaolson1** [vinjn/awesome-vulkan#21]
The widely used [Skia](https://skia.org) 2D graphics library has a working [Vulkan](https://skia.org/user/special/vulkan) [backend](https://github.com/google/skia/tree/master/src/gpu/vk).

There is also a kind of [sample](https://skia.org/user/sample/viewer) [app](https://github.com/google/skia/tree/master/tools/viewer).

Skia's main page claims that its [license](https://github.com/google/skia/blob/master/LICENSE) is some kind of BSD.

Note to self/others: [PR guidelines](https://github.com/vinjn/awesome-vulkan/blob/master/CONTRIBUTING.md).

**Comment by vinjn** [comment]
Can you send out a PR?

**Comment by 0joshuaolson1** [comment]
Sure. Before I do, do you think this falls under "Vulkan libraries, debuggers and resources"?

**Comment by sjfricke** [comment]
Well, there isn't a resource or debugger sub category and I feel it would personally go in Libraries since a lot of the libraries such as Cinder are tools that have created a Vulkan backend for it.

**Comment by vinjn** [comment]
I would also suggest go in Libraries.

**Comment by 0joshuaolson1** [comment]
Okay.

**Comment by 0joshuaolson1** [comment]
To close when #29 is merged.
