### ISSUE TITLE
You are listing a broken binding for the DLang (vulkanized)

### ISSUE THREAD

**Issue by ParticlePeter** [vinjn/awesome-vulkan#4]
The vulkanized vulkan binding is not working due to wrong usage of the d type system. Please list [dvulkan](https://github.com/ColonelThirtyTwo/dvulkan) binding instead. Additionally and contrary to vulkanized binding, python is used to auto generate correct bindings from the Khrons vulkan docs.

**Comment by vinjn** [comment]
Done, thx.
